services:
  java_app:
    container_name: java_app
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - java_db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://java_db:5432/market-simulation
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: mypassword
    ports:
      - 8080:8080

  java_db:
    container_name: java_db
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: market-simulation
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
    pg_data: {}